# Welcome to Jekyll!
title: Hanaé &hearts; Bouquand
url:
baseurl:

# Sass setting
sass:
  sass_dir: _sass
  style:    compressed

# Custom
lang: fr                    # html lang
open: true                  # open or close your site
date_format: "%Y-%m-%d"     # date format
theme_color: "#FF478A"      # your favorite theme color
allow_search_engines: false # allow search engines indexing your resume
analytics:
  google:                   # your google analytics
  cloudflare:               # your cloudflare analytics
